### ISSUE TITLE
npm: Ignore @types packages

### ISSUE THREAD

**Issue by K3UL** [AppThreat/dep-scan#10]
Hi,

Unless I misread the situation and the typing package is actually not secure, dep-scan considers a types package and the "regular" package as the same.

For example I use the latest `morgan` package (v1.10.0) right now, and the scanner (I use docker run) gives me no vulnerability.

If I install the latest `@types/morgan`, which happens to be v1.9.0, I then get a medium vulnerability `Code Injection`.
I did the test of removing `morgan@1.10.0` and `@types/morgan` and installing `morgan@1.9.0` and I get the same vulnerability.

So I think for npm, the scanner needs to ignore `@types/*` packages since they are devDependencies anyway.

Thank you !

**Comment by prabhu** [comment]
This is now fixed here - https://github.com/AppThreat/cdxgen/commit/02b199cb0a0d074000aeeda739d332011a278fb7

Instead of removing all dev dependencies I decided to exclude only selective packages. This is because many production deployments for node js doesn't correctly use `--only=production` flag. Can you test and let me know if it works correctly now?

**Comment by K3UL** [comment]
Hello @prabhu,

Sorry for the delay and thank you for the fix, it seems to be fixed !

**Comment by prabhu** [comment]
Thank you for confirming! @K3UL
