### ISSUE TITLE
TypeError in `license.py`

### ISSUE THREAD

**Issue by ocrawford555** [AppThreat/dep-scan#17]
Hi!

Tool works fine for some Python projects and Java + Node projects. Whilst testing out the tool for one Python project, found a small bug. Not sure what the root cause is yet, so just adding some context here. Fix should be simple enough.

Command:
```bash
scan --src $PWD --report_file $PWD/reports/depscan.json
``` 

Output:
```bash
INFO [2020-07-22 10:34:14,830] ================================================================================
Traceback (most recent call last):
  File "/usr/local/bin/scan", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/depscan/cli.py", line 234, in main
    build_license_data(license_data_dir), pkg_list=pkg_list
  File "/usr/local/lib/python3.7/site-packages/depscan/lib/license.py", line 35, in bulk_lookup
    pkg_key = pkg["vendor"] + ":" + pkg["name"] + "@" + pkg["version"]
TypeError: can only concatenate str (not "NoneType") to str
```

A fix would just be to use some string formatting or handle the case of None. Not sure why None is being introduced, if I have more time I will try and track down more. For now I tried this fix which allowed the scan to complete successfully.

```python
pkg_key = f"{pkg['vendor']}:{pkg['name']}@{pkg['version']}"
```

Cheers

**Comment by prabhu** [comment]
There was a regression briefly in cdxgen which was pushing out null values in JS mode. Looks like you have caught this issue at the wrong moment. Thank you for the suggested fix. I'm in the process of changing the key format for license so that it will become name@version if there are no vendor information. Will leave a comment once the new version is available which additionally would bring ruby support if that is a thing.

Also not sure how you are using dep-scan but feel free to try out the parent project `scan` which also includes depscan and the correct version of dependencies. https://slscan.io/en/latest/

**Comment by ocrawford555** [comment]
Sweet, will look into it, thanks! Feel free to close the issue off when you think it's fixed.

**Comment by prabhu** [comment]
This is resolved. Thanks for your help!
