### ISSUE TITLE
Log4J (CVE-2021-44228) was considered as low severity vulnerability 

### ISSUE THREAD

**Issue by kakumanivrn** [AppThreat/dep-scan#58]
I have scanned a vulnerable log4j repo just for testing and found that `CVE-2021-44228` is considered as low severity. 

Repository used for scanning: https://github.com/christophetd/log4shell-vulnerable-app

Attaching the screenshot for reference:
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/4201693/173490902-0ad3ed95-d2a0-491d-ae90-10c600ffba65.png">

**Comment by prabhu** [comment]
Thanks, @kakumanivrn, for raising this issue. This is fixed with 2.1.4

![Snag_2d0525](https://user-images.githubusercontent.com/7842/173591207-5fcf8641-4ad9-4d9a-87c4-d74154795a78.png)

Perhaps a bug or the format of OSV schema had changed recently; severity is now appearing in the root instead of under the affected array in the OSV feed.
https://github.com/AppThreat/vulnerability-db/commit/a45fc845257b963f079130d504debae3ea7282ec

**Comment by kakumanivrn** [comment]
@prabhu thank you so much for the quick fix! Is this because of the static severity or due to using older version of the vulnerability database? I see that you are using static version for the vulnerability database. Can this be automated?

**Comment by prabhu** [comment]
could you remove the existing vulnerbility database. The location would be printed by depscan usually `$HOME/.local/share/vdb`

**Comment by kakumanivrn** [comment]
Thanks @prabhu! This worked after I deleted db files and cached again. 

But I also did `--cache` and `--sync` before deleting the files as well, but maybe somehow the files were not really replaced. I think it might be a bug in vdb. I tried understanding the code but I wasn't able to figure out.

**Comment by prabhu** [comment]
`--clean` is used to remove the database. Both the --cache and --sync will append to the existing database.
